controllers:
    resource: ../src/Controller/
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: attribute

# dashboard:
#     path: /admin
#     controller: App\Controller\Admin\DashboardController::index
